export const  data = [
    {
        id:1,
        identity:"morales",
        country:"kenya",
        color:"red"
    },,
    {
        id:1,
        identity:"morales",
        country:"kenya",
        color:"red"
    },
    {
        id:1,
        identity:"morales",
        country:"kenya",
        color:"red"
    },
    {
        id:1,
        identity:"morales",
        country:"kenya",
        color:"red"
    },
    {
        id:1,
        identity:"morales",
        country:"kenya",
        color:"red"
    }
]

